window.data = {
    coffee: 0,
    totalCPS: 0,
    producers: [
        {
            id: 'chemex',
            price: 10,
            unlocked: false,
            cps: 1,
            qty: 0,
        },
        {
            id: 'cóvfefe_press',
            price: 50,
            unlocked: false,
            cps: 2,
            qty: 0,
        },
        {
            id: 'mr._covfefe',
            price: 100,
            unlocked: false,
            cps: 5,
            qty: 0,
        },
        {
            id: 'ten_cup_urn',
            price: 500,
            unlocked: false,
            cps: 10,
            qty: 0,
        },
        {
            id: 'espresso_machine',
            price: 1000,
            unlocked: false,
            cps: 20,
            qty: 0,
        },
        {
            id: 'ten_gallon_urn',
            price: 5000,
            unlocked: false,
            cps: 50,
            qty: 0,
        },
        {
            id: 'covfefeshop',
            price: 10000,
            unlocked: false,
            cps: 75,
            qty: 0,
        },
        {
            id: 'covfefe_factory',
            price: 50000,
            unlocked: false,
            cps: 100,
            qty: 0,
        },
        {
            id: 'covfefe_fountain',
            price: 100000,
            unlocked: false,
            cps: 200,
            qty: 0,
        },
        {
            id: 'covfefe_river',
            price: 500000,
            unlocked: false,
            cps: 500,
            qty: 0,
        },
        {
            id: 'covfefe_ocean',
            price: 1000000,
            unlocked: false,
            cps: 1000,
            qty: 0,
        },
        {
            id: 'covfefe_planet',
            price: 5000000,
            unlocked: false,
            cps: 2000,
            qty: 0,
        },
    ],
};
